### PR TITLE
Adding the requirements.txt file so that we can house all build tool …

### PR DESCRIPTION
**Pull request by ctorboh15**
…requirements for python in a single file. The command was already pretty beefy so this seemed like a better long term maintainable solutuion. Also I added a pip freeze so we can tell exactly what is pip libraries have been installed and versions.

### CODE REVIEW

**Comment by wms** [comment]
Nice. Does this mean we can remove all of the explicit packages from the line above (`pip install --upgrade awscli==1.14.5 s3cmd==2.0.1 python-magic yq`) into `requirements.txt`?

**Comment by ctorboh15** [comment]
> Nice. Does this mean we can remove all of the explicit packages from the line above (`pip install --upgrade awscli==1.14.5 s3cmd==2.0.1 python-magic yq`) into `requirements.txt`?

yes it does!

**Comment by ctorboh15** [comment]
@wms I think we can build this ... it will be tagged as latest but if something goes wrong we can always untag it and delete it. Luckily drone is configured to pull the latest tag so we have a pretty safe exit plan. Im not sure where we host this image. It is not in ECR so maybe dockerhub?

**Comment by wms** [comment]
>  It is not in ECR so maybe dockerhub?

Correct - https://hub.docker.com/r/ailabsteam/infrastructure-tools

Looks like the build is failing due to our long-forgotten CircleCI account.

**Pull request merged**
